[StyleCorporate]
FontFace=#FontCorporate#
FontColor=#TextBlack#
AntiAlias=1

[StyleEngineering]
FontFace=#FontEngineering#
FontColor=#TextBlack#
AntiAlias=1

[StyleData]
FontFace=#FontData#
FontColor=#TextBlack#
AntiAlias=1

[StyleMuted]
FontFace=#FontData#
FontColor=#TextGray#
AntiAlias=1

[StyleSection]
FontFace=#FontEngineering#
FontSize=9
FontWeight=700
FontColor=#DeepBlue#
AntiAlias=1
StringCase=Upper
